version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
    ports:
      - 27017:27017
  results-worker:
    depends_on:
      - mongodb
    build: ./results-worker/.
    restart: unless-stopped
    environment:
      - BASE_URL=http://35.207.169.147
      - MONGO_CONNECTIONSTRING=mongodb://AzureDiamond:hunter2@mongodb:27017
      - AUTH_PASSWORD=lTgAYaLP9jRs
  web-app:
    depends_on:
      - mongodb
    build: ./web-app/.
    restart: unless-stopped
    ports:
      - 7000:7000
    environment:
      - PORT=7000
      - MONGO_CONNECTIONSTRING=mongodb://AzureDiamond:hunter2@mongodb:27017
